/**
 * Compile brand + shared design tokens into a single CSS file consumed by
 * `app/globals.css`. Tailwind v4 is CSS-first, so the output is plain CSS
 * variables grouped by selector:
 *
 *   :root                                          — theme/brand-invariant
 *   :root[data-brand="bayan"][data-theme="light"]  — brand × theme color vars
 *
 * Style Dictionary is used as a formatter so the pipeline stays conventional
 * (per CLAUDE.md → "Tokens → Tailwind preset"), but the emission shape is
 * bespoke: we collapse the per-color `{ light, dark }` object into a single
 * variable per theme and strip the theme suffix from the CSS name.
 */
import { mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import StyleDictionary from "style-dictionary";

type Brand = "bayan" | "alt";
type Theme = "light" | "dark";

const BRANDS: Brand[] = ["bayan", "alt"];

const SOURCE_DIR = path.resolve("tokens/source");
const BUILD_DIR = path.resolve("tokens/build");
const OUT_FILE = path.join(BUILD_DIR, "tokens.css");

const toKebab = (s: string): string => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

// Emit `--color-primary: #…` for tokens whose path ends in the matching
// theme; emit theme-invariant tokens under `:root`.
async function buildCss(): Promise<string> {
  const sharedRaw = JSON.parse(await readFile(path.join(SOURCE_DIR, "_shared.json"), "utf8"));

  const baseLines: string[] = [];
  const walk = (node: Record<string, unknown>, prefix: string[]): void => {
    for (const [key, value] of Object.entries(node)) {
      if (value && typeof value === "object" && "value" in (value as Record<string, unknown>)) {
        const name = [...prefix, key].map(toKebab).join("-");
        baseLines.push(`  --${name}: ${(value as { value: string }).value};`);
      } else if (value && typeof value === "object") {
        walk(value as Record<string, unknown>, [...prefix, key]);
      }
    }
  };
  walk(sharedRaw, []);

  const blocks: string[] = [`:root {\n${baseLines.join("\n")}\n}`];

  // For each brand emit four rules:
  //   1. `:root[data-brand="X"]`                       — default = light
  //   2. `@media (prefers-color-scheme: dark)` → same  — system-pref dark
  //   3. `:root[data-brand="X"][data-theme="light"]`   — explicit light
  //   4. `:root[data-brand="X"][data-theme="dark"]`    — explicit dark
  // CSS alone paints the right theme on the very first frame for system-pref
  // users, so we need no pre-hydration JS to prevent FOUC. Explicit
  // `[data-theme]` overrides win via specificity regardless of source order.
  for (const brand of BRANDS) {
    const brandRaw = JSON.parse(await readFile(path.join(SOURCE_DIR, `${brand}.json`), "utf8"));

    const buildBody = async (theme: Theme): Promise<string> => {
      const sd = new StyleDictionary({
        tokens: brandRaw,
        log: { verbosity: "silent" },
        platforms: {
          css: {
            transformGroup: "css",
            files: [
              { destination: `${brand}-${theme}.css`, format: "css/themed", options: { theme } },
            ],
          },
        },
      });
      sd.registerFormat({
        name: "css/themed",
        format: ({ dictionary, options }) => {
          const lines: string[] = [];
          for (const t of dictionary.allTokens) {
            const last = t.path[t.path.length - 1];
            if (last !== "light" && last !== "dark") continue;
            if (last !== options.theme) continue;
            const name = t.path.slice(0, -1).map(toKebab).join("-");
            lines.push(`  --${name}: ${t.$value ?? t.value};`);
          }
          return lines.join("\n");
        },
      });
      const out = (await sd.formatPlatform("css")) as Array<{ output?: string }>;
      return out[0]?.output ?? "";
    };

    const lightBody = await buildBody("light");
    const darkBody = await buildBody("dark");

    blocks.push(`:root[data-brand="${brand}"] {\n${lightBody}\n}`);
    blocks.push(
      `@media (prefers-color-scheme: dark) {\n  :root[data-brand="${brand}"] {\n${darkBody
        .split("\n")
        .map((l) => (l ? `  ${l}` : l))
        .join("\n")}\n  }\n}`,
    );
    blocks.push(`:root[data-brand="${brand}"][data-theme="light"] {\n${lightBody}\n}`);
    blocks.push(`:root[data-brand="${brand}"][data-theme="dark"] {\n${darkBody}\n}`);
  }

  return [
    "/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */",
    "",
    ...blocks,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  if (existsSync(BUILD_DIR)) await rm(BUILD_DIR, { recursive: true });
  await mkdir(BUILD_DIR, { recursive: true });
  const css = await buildCss();
  await writeFile(OUT_FILE, css, "utf8");
  process.stdout.write(`wrote ${path.relative(process.cwd(), OUT_FILE)}\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
